#118_fix_km
ASO1901029/sk2020_5K pull request #142
Opened 2020-10-22 16:34 UTC by Koresue

ユーザname更新の際にアクションを追加

2020-10-23 03:05 UTC, ASO1901029 requested changes

2020-10-23 03:05 UTC, ASO1901029 commented on 04.source/ideash/app/controllers/users/registrations_controller.rb
> +  def profile_edit()
()はなくていいです（特に引数が無いので）

2020-10-23 03:05 UTC, ASO1901029 commented on 04.source/ideash/app/controllers/users/registrations_controller.rb
> +    @is_updated_check = true
変数名から中身が分かりづらいです・・

2020-10-23 03:05 UTC, ASO1901029 commented on 04.source/ideash/app/javascript/packs/user/account.js
> +    console.log (is_updated);
不要なconsole.logを残さないで・・

2020-10-27 01:10 UTC, CatsManma approved these changes
確認しました

2020-10-27 01:13 UTC, ASO1901029 approved these changes

2020-10-27 01:14 UTC, merged